# This is a basic workflow to help you get started with Actions

name: brewall Syntax Check

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ nightly ]
  pull_request:
    branches: [ nightly ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: macos-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        env:
          IS_DEBUG: TRUE

      # Runs a single command using the runners shell
      - name: Install Homebrew and initialize brewall
        run: $GITHUB_WORKSPACE/brewall.sh
        
      # Runs a set of commands using the runners shell  
      - name: Print brewall runtime
        run: $GITHUB_WORKSPACE/brewall.sh runtime
      - name: Print brewall version
        run: $GITHUB_WORKSPACE/brewall.sh version
      - name: Print brewall changelog
        run: $GITHUB_WORKSPACE/brewall.sh changelog
      - name: brewall config files delete
        run: $GITHUB_WORKSPACE/brewall.sh remove --config
